[package]
name = "verifythis-verus"
version = "0.1.0"
edition = "2024"

[dependencies]
vstd =           { git = "https://github.com/verus-lang/verus" }
builtin =        { git = "https://github.com/verus-lang/verus" }
builtin_macros = { git = "https://github.com/verus-lang/verus" }
